#%RAML 1.0 DataType
  type: object
  properties:
    name:
      type: string
      example: "ORACLE SOA"
      required: true
    description:
      type: string
      required: true
      example: "Middleware integration tool"                
    author:
      type: string
      required: true
      example: "Arun"
    Price:
      type: number
      required: true
      example: 2000
    Duration:
      type: string
      required: true
      example: "8hrs"