#%RAML 1.0 Library
types:
  coursetype:
    properties:
      name:
        type: string
        required: true
        example: "Harry potter"
      description:
        type: string
        required: true
        example: "Entertainment"                
      author:
        type: string
        required: true
        example: "JK Rowling"
      Price:
        type: number
        required: true
        example: 2000
      Duration:
        type: string
        required: true
        example: "2hrs"